INSERT INTO region VALUES ('1','Piemonte','1','TO','Torino'),
('1','Piemonte','2','VC','Vercelli'),
('1','Piemonte','3','NO','Novara'),
('1','Piemonte','4','CN','Cuneo'),
('1','Piemonte','5','AT','Asti'),
('1','Piemonte','6','AL','Alessandria'),
('2','Valle d Aosta','7','AO','Aosta'),
('7','Liguria','8','IM','Imperia'),
('7','Liguria','9','SV','Savona'),
('7','Liguria','10','GE','Genova'),
('7','Liguria','11','SP','La Spezia'),
('3','Lombardia','12','VA','Varese'),
('3','Lombardia','13','CO','Como'),
('3','Lombardia','14','SO','Sondrio'),
('3','Lombardia','15','MI','Milano'),
('3','Lombardia','16','BG','Bergamo'),
('3','Lombardia','17','BS','Brescia'),
('3','Lombardia','18','PV','Pavia'),
('3','Lombardia','19','CR','Cremona'),
('3','Lombardia','20','MN','Mantova'),
('4','Trentino-Alto Adige','21','BZ','Bolzano'),
('4','Trentino-Alto Adige','22','TN','Trento'),
('5','Veneto','23','VR','Verona'),
('5','Veneto','24','VI','Vicenza'),
('5','Veneto','25','BL','Belluno'),
('5','Veneto','26','TV','Treviso'),
('5','Veneto','27','VE','Venezia'),
('5','Veneto','28','PD','Padova'),
('5','Veneto','29','RO','Rovigo'),
('6','Friuli-Venezia Giulia','30','UD','Udine'),
('6','Friuli-Venezia Giulia','31','GO','Gorizia'),
('6','Friuli-Venezia Giulia','32','TS','Trieste'),
('8','Emilia-Romagna','33','PC','Piacenza'),
('8','Emilia-Romagna','34','PR','Parma'),
('8','Emilia-Romagna','35','RE','Reggio nell Emilia'),
('8','Emilia-Romagna','36','MO','Modena'),
('8','Emilia-Romagna','37','BO','Bologna'),
('8','Emilia-Romagna','38','FE','Ferrara'),
('8','Emilia-Romagna','39','RA','Ravenna'),
('8','Emilia-Romagna','40','FO','Forli-Cesena'),
('11','Marche','41','PS','Pesaro e Urbino'),
('11','Marche','42','AN','Ancona'),
('11','Marche','43','MC','Macerata'),
('11','Marche','44','AP','Ascoli Piceno'),
('9','Toscana','45','MS','Massa-Carrara'),
('9','Toscana','46','LU','Lucca'),
('9','Toscana','47','PT','Pistoia'),
('9','Toscana','48','FI','Firenze'),
('9','Toscana','49','LI','Livorno'),
('9','Toscana','50','PI','Pisa'),
('9','Toscana','51','AR','Arezzo'),
('9','Toscana','52','SI','Siena'),
('9','Toscana','53','GR','Grosseto'),
('10','Umbria','54','PG','Perugia'),
('10','Umbria','55','TR','Terni'),
('12','Lazio','56','VT','Viterbo'),
('12','Lazio','57','RI','Rieti'),
('12','Lazio','58','RM','Roma'),
('12','Lazio','59','LT','Latina'),
('12','Lazio','60','FR','Frosinone'),
('15','Campania','61','CE','Caserta'),
('15','Campania','62','BN','Benevento'),
('15','Campania','63','NA','Napoli'),
('15','Campania','64','AV','Avellino'),
('15','Campania','65','SA','Salerno'),
('13','Abruzzo','66','AQ','Aquila'),
('13','Abruzzo','67','TE','Teramo'),
('13','Abruzzo','68','PE','Pescara'),
('13','Abruzzo','69','CH','Chieti'),
('14','Molise','70','CB','Campobasso'),
('16','Puglia','71','FG','Foggia'),
('16','Puglia','72','BA','Bari'),
('16','Puglia','73','TA','Taranto'),
('16','Puglia','74','BR','Brindisi'),
('16','Puglia','75','LE','Lecce'),
('17','Basilicata','76','PZ','Potenza'),
('17','Basilicata','77','MT','Matera'),
('18','Calabria','78','CS','Cosenza'),
('18','Calabria','79','CZ','Catanzaro'),
('18','Calabria','80','RC','Reggio di Calabria'),
('19','Sicilia','81','TP','Trapani'),
('19','Sicilia','82','PA','Palermo'),
('19','Sicilia','83','ME','Messina'),
('19','Sicilia','84','AG','Agrigento'),
('19','Sicilia','85','CL','Caltanissetta'),
('19','Sicilia','86','EN','Enna'),
('19','Sicilia','87','CT','Catania'),
('19','Sicilia','88','RG','Ragusa'),
('19','Sicilia','89','SR','Siracusa'),
('20','Sardegna','90','SS','Sassari'),
('20','Sardegna','91','NU','Nuoro'),
('20','Sardegna','92','CA','Cagliari'),
('6','Friuli-Venezia Giulia','93','PN','Pordenone'),
('14','Molise','94','IS','Isernia'),
('20','Sardegna','95','OR','Oristano'),
('1','Piemonte','96','BI','Biella'),
('3','Lombardia','97','LC','Lecco'),
('3','Lombardia','98','LO','Lodi'),
('8','Emilia-Romagna','99','RN','Rimini'),
('9','Toscana','100','PO','Prato'),
('18','Calabria','101','KR','Crotone'),
('18','Calabria','102','VV','Vibo Valentia'),
('1','Piemonte','103','VB','Verbano-Cusio-Ossola');