INSERT INTO Region(codice, nome) VALUES 
    ('1', 'Piemonte'),
    ('2', 'Valle d Aosta'),
    ('3', 'Lombardia'),
    ('4', 'Trentino-Alto Adige'),
    ('5', 'Veneto'),
    ('6', 'Friuli-Venezia Giulia'),
    ('7', 'Liguria'),
    ('8', 'Emilia-Romagna'),
    ('9', 'Toscana'),
    ('10', 'Umbria'),
    ('11', 'Marche'),
    ('12', 'Lazio'),
    ('13', 'Abruzzo'),
    ('14', 'Molise'),
    ('15', 'Campania'),
    ('16', 'Puglia'),
    ('17', 'Basilicata'),
    ('18', 'Calabria'),
    ('19', 'Sicilia'),
    ('20', 'Sardegna');

INSERT INTO Province(Regione,codice,iniziali,nome) VALUES 
    ('1','1','TO','Torino'),
    ('1','2','VC','Vercelli'),
    ('1','3','NO','Novara'),
    ('1','4','CN','Cuneo'),
    ('1','5','AT','Asti'),
    ('1','6','AL','Alessandria'),
    ('2','7','AO','Aosta'),
    ('7','8','IM','Imperia'),
    ('7','9','SV','Savona'),
    ('7','10','GE','Genova'),
    ('7','11','SP','La Spezia'),
    ('3','12','VA','Varese'),
    ('3','13','CO','Como'),
    ('3','14','SO','Sondrio'),
    ('3','15','MI','Milano'),
    ('3','16','BG','Bergamo'),
    ('3','17','BS','Brescia'),
    ('3','18','PV','Pavia'),
    ('3','19','CR','Cremona'),
    ('3','20','MN','Mantova'),
    ('4','21','BZ','Bolzano'),
    ('4','22','TN','Trento'),
    ('5','23','VR','Verona'),
    ('5','24','VI','Vicenza'),
    ('5','25','BL','Belluno'),
    ('5','26','TV','Treviso'),
    ('5','27','VE','Venezia'),
    ('5','28','PD','Padova'),
    ('5','29','RO','Rovigo'),
    ('6','30','UD','Udine'),
    ('6','31','GO','Gorizia'),
    ('6','32','TS','Trieste'),
    ('8','33','PC','Piacenza'),
    ('8','34','PR','Parma'),
    ('8','35','RE','Reggio nell Emilia'),
    ('8','36','MO','Modena'),
    ('8','37','BO','Bologna'),
    ('8','38','FE','Ferrara'),
    ('8','39','RA','Ravenna'),
    ('8','40','FO','Forli-Cesena'),
    ('11','41','PS','Pesaro e Urbino'),
    ('11','42','AN','Ancona'),
    ('11','43','MC','Macerata'),
    ('11','44','AP','Ascoli Piceno'),
    ('9','45','MS','Massa-Carrara'),
    ('9','46','LU','Lucca'),
    ('9','47','PT','Pistoia'),
    ('9','48','FI','Firenze'),
    ('9','49','LI','Livorno'),
    ('9','50','PI','Pisa'),
    ('9','51','AR','Arezzo'),
    ('9','52','SI','Siena'),
    ('9','53','GR','Grosseto'),
    ('10','54','PG','Perugia'),
    ('10','55','TR','Terni'),
    ('12','56','VT','Viterbo'),
    ('12','57','RI','Rieti'),
    ('12','58','RM','Roma'),
    ('12','59','LT','Latina'),
    ('12','60','FR','Frosinone'),
    ('15','61','CE','Caserta'),
    ('15','62','BN','Benevento'),
    ('15','63','NA','Napoli'),
    ('15','64','AV','Avellino'),
    ('15','65','SA','Salerno'),
    ('13','66','AQ','Aquila'),
    ('13','67','TE','Teramo'),
    ('13','68','PE','Pescara'),
    ('13','69','CH','Chieti'),
    ('14','70','CB','Campobasso'),
    ('16','71','FG','Foggia'),
    ('16','72','BA','Bari'),
    ('16','73','TA','Taranto'),
    ('16','74','BR','Brindisi'),
    ('16','75','LE','Lecce'),
    ('17','76','PZ','Potenza'),
    ('17','77','MT','Matera'),
    ('18','78','CS','Cosenza'),
    ('18','79','CZ','Catanzaro'),
    ('18','80','RC','Reggio di Calabria'),
    ('19','81','TP','Trapani'),
    ('19','82','PA','Palermo'),
    ('19','83','ME','Messina'),
    ('19','84','AG','Agrigento'),
    ('19','85','CL','Caltanissetta'),
    ('19','86','EN','Enna'),
    ('19','87','CT','Catania'),
    ('19','88','RG','Ragusa'),
    ('19','89','SR','Siracusa'),
    ('20','90','SS','Sassari'),
    ('20','91','NU','Nuoro'),
    ('20','92','CA','Cagliari'),
    ('6','93','PN','Pordenone'),
    ('14','94','IS','Isernia'),
    ('20','95','OR','Oristano'),
    ('1','96','BI','Biella'),
    ('3','97','LC','Lecco'),
    ('3','98','LO','Lodi'),
    ('8','99','RN','Rimini'),
    ('9','100','PO','Prato'),
    ('18','101','KR','Crotone'),
    ('18','102','VV','Vibo Valentia'),
    ('1','103','VB','Verbano-Cusio-Ossola');